# API Gateway 설정 파일

# 서버 포트 설정
server:
  port: 8080  # API Gateway는 엔드유저가 접속하는 진입점이로 8080 표준 HTTP 포트 사용

spring:
  application:
    name: api-gateway  # Config Server에서 이 이름으로 설정을 가져옵니다
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # Eureka에서 서비스를 자동으로 찾아서 라우팅합니다
          lower-case-service-id: true  # 서비스 ID를 소문자로 변환합니다
      routes:  # 라우팅 규칙 정의
        # 사용자 서비스 라우팅
        - id: user-service  # 라우트 식별자
          uri: lb://USER-SERVICE  # 대상 서비스 (lb:// 접두사는 로드밸런싱을 의미)
          predicates:  # 매칭될 경로 패턴들
            - Path=/api/users/**, /api/members/**, /api/enterprises/**
        
        # 상품 서비스 라우팅
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**, /api/categories/**
        
        # 주문 서비스 라우팅
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        
        # 결제 서비스 라우팅
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**, /api/refunds/**

# Eureka 클라이언트 설정
eureka:
  client:
    fetch-registry: true         # Eureka에서 서비스 정보를 가져옵니다
    register-with-eureka: true   # 이 서비스를 Eureka에 등록합니다
